services:
  postgres:
   image: postgres
   deploy:
     replicas: 3
   environment: 
    POSTGRES_PASSWORD: 123456
    POSTGRES_USER: postgres
    POSTGRES_DB: hospital_db
   ports:
    - "5433:5432"
   volumes:
    - postgres-final:/var/lib/postgresql/data
   networks:
    - hospital-network
  backend:
   image: dockerv5-backend
   deploy:
     replicas: 3
     update_config:
       parallelism: 1
       delay: 10s
     restart_policy:
       condition: on-failure
   environment: 
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hospital_db
   ports:
    - "9700:9700"
   depends_on:
    - postgres
   networks:
    - hospital-network
  frontend:
   image: dockerv5-frontend
   deploy:
     replicas: 3
     update_config:
       parallelism: 1
       delay: 10s
     restart_policy:
       condition: on-failure
   ports:
    - "4200:4200"
   depends_on:
    - backend
   networks:
    - hospital-network
networks:
 hospital-network:
  driver: overlay
volumes:
  postgres-final:
  