services:
  mysql:
   image: mysql:8.1
   restart: always
   environment: 
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: laravel_vue
    MYSQL_USER: root1
    MYSQL_PASSWORD: root1
   ports:
    - "3306"
   volumes:
    - mysql-final:/var/lib/mysql
   networks:
    - laravelvue-network
  backend:
   build:
    context: ./backend_laravel/
    dockerfile: Dockerfile
   restart: always
   networks:
    - laravelvue-network
  frontend:
   build:
    context: ./frontend_vue
    dockerfile: Dockerfile
   restart: always
   ports:
    - "3000"
   networks:
    - laravelvue-network
  webserver: 
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    depends_on:
     - backend
     - frontend
    restart: always
    ports:
     - "80:80"
    networks:
     - laravelvue-network     
networks:
 laravelvue-network:
volumes:
  mysql-final:
  